# .github/workflows/nadavs-tmp-workflow.yml
name: Test Notebooks

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run notebook tests
        uses: ./.github/actions/run-tests  # Calls your composite action
        with:
          env: dev  # Example environment
          notebooks: notebook1.ipynb,notebook2.ipynb  # List of notebooks to be tested
        env:
          PROD_M2M_SECRET_ARN: ${{ secrets.PROD_M2M_SECRET_ARN }}  # Passing secrets
          NIGHTLY_M2M_SECRET_ARN: ${{ secrets.NIGHTLY_M2M_SECRET_ARN }}  # Passing secrets